### ISSUE TITLE
Scope out short-term project design needs in more detail

### ISSUE THREAD

**Issue by alexsoble** [18F/OPRE-Unicorn#101]
### Goals
Create a list of the design needs on the project: short, medium, & long term. 

### Additional Context
@ninamak has a [microrequest](https://gsa-tts.slack.com/archives/CNFHBCXDW/p1627068847005100) for design support to help us rescope our staffing request.  This list of needs could be helpful in that conversation.

### End result

We scoped out our short term design needs here: https://github.com/18F/OPRE-Unicorn/issues/101#issuecomment-887717793

... and a wonderful designer joined our team!

**Comment by ninamak** [comment]
Scheduled for Thurs 7/28 co-work

**Comment by alexsoble** [comment]
## Team brainstorming on design needs 7/27/2021

Brainstorming with: @ninamak @carjug @amymok @alexsoble.

### Short term: user research

**Goal**: As a team, we need to understand our user needs in more depth in order to make better decisions about the product we are building with OPRE.

We want user research to help us decide:

* which data tables in the current product we should focus on
*  and how we should change or transform the data ...

... in order to meet the user needs in our "first slice". 🍰 

We think that in order to achieve these goals, we will need the following: 

* Review existing user research, user stories, and prototype. 
* Create a user research plan focused on our ["first slice use cases"](https://docs.google.com/presentation/d/1BxbDWAz5Ay2fnHSPEKa9votY-LoAYiwqXWxOBr6EwnY/edit#slide=id.ge5fd088427_0_148) — OPRE Division Director, Team Lead, and COR users. Prioritize which users and which questions to start with.
* Interview users who need to review budget information. 
* Synthesize research findings with focus on:
  * how different users want to see and work with data 
  * which data we will need to support user needs 
  * areas of potential misalignment within OPRE
* Validate initial findings with users. 

The above tasks could potentially be split between different people, if needed.

**Comment by alexsoble** [comment]
☝️ We know our project will have product design and UX needs as well, but we think the product design & UX will need to be informed by the user research scoped above.

**Comment by alexsoble** [comment]
How about we break this issue up into two — "scope out short term design needs", "scope out medium/long term design needs" — call the first part Done and the second part we can prioritize and complete in a future cycle?

**Comment by ninamak** [comment]
Sounds good to me!  I think the idea is that Julia will help with that second part.

**Comment by alexsoble** [comment]
Broke out medium- and long-term into its own issue: https://github.com/18F/OPRE-Unicorn/issues/107
