### ISSUE TITLE
Consolidate "How We Work" docs

### ISSUE THREAD

**Issue by ninamak** [18F/OPRE-Unicorn#110]
In our repo, our "how we work"-related docs are spread out in a couple places and should all live in one place.

See https://github.com/18F/OPRE-Unicorn/tree/main/docs

We have: 
* how_we_work.md
* how_we_work folder
  * estimation.md
  * issue_review.md (currently in PR)

**Comment by carjug** [comment]
Everyone cool with me moving the current `how_we_work.md` (which contains our engineering practices only) to the `how_we_work` folder under the name `engineering_practices.md`? CC: @ninamak @alexsoble @amymok

**Comment by alexsoble** [comment]
@carjug Yep! That's a better filename!
