### ISSUE TITLE
Decide on tech services needed for version control

### ISSUE THREAD

**Issue by carjug** [18F/OPRE-Unicorn#26]
As a team, we need to agree upon which technologies we will be using for version control.

Table for reference:

  | Carly | Amy | Alex
-- | -- | -- | --
Technology for version control | GitHub | GitHub | GitHub

**Tasks**

- [ ] Determine technology for version control and document with a lightweight decision record
- [ ] Create "procurement" and/or any implementation follow on tasks for version control

**Comment by carjug** [comment]
@amymok @alexsoble do we think this is work we could do asynchronously? if so, we can perhaps start a doc with our thoughts there or capture our thoughts in the Running Notes doc? Just a thought. Trying to see how we can collaborate on these tasks while also being efficient with everyone's time :)

**Comment by amymok** [comment]
That works! We can continue with what we were doing in the running notes for the team processes.

**Comment by alexsoble** [comment]
[Async discussion in the running notes.](https://docs.google.com/document/d/1ZfdtFVgrXBwxWsH2ur_JtIcy5EslvlZYzqW2rPnZz-k/edit#heading=h.fv8f0cbosyo9)

**Comment by alexsoble** [comment]
This will be an early ADR!

@carjug @amymok and I will pair on this together, and tag in @ninamak for review as part of a "bundle" of early ADRs.

:oneteamonedream:

**Comment by carjug** [comment]
The goal is to have this moved into "In Review" by EOD tomorrow :)

**Comment by alexsoble** [comment]
We are discussing GitHub vs. GitHub Enterprise and are curious which one HHS is using — @carjug will ask our contact at HHS when she emails him. 

If GitHub Enterprise, the version being used would determine what features are / are not available.

**Comment by alexsoble** [comment]
During eng coworking we decided to split this into two issues — one for version control and one for continuous integration.

Will rename this card to refer to version control services and make a new card for continuous integration services.

**Comment by alexsoble** [comment]
Scoped this down to just version control and split off CI/CD into its own ticket: https://github.com/18F/OPRE-MAPS/issues/55.

**Comment by alexsoble** [comment]
[closed and re-opened by accident!]
