### ISSUE TITLE
Create skeleton system architecture and diagram

### ISSUE THREAD

**Issue by carjug** [18F/OPRE-Unicorn#27]
As a team, we need a rough outline for how our application will work so that we have a shared understanding and can divide up our work and plan the build of Unicorn accordingly.

At a level of detail suitable for team's own common understanding.

Pref to do this work collaboratively rather than async.

**Tasks**

- [x] Determine what diagramming software we want to use (OCIO may have a preference here)
- [x] Determine skeleton system architecture and document with a lightweight decision record and architecture diagram

**Resources**
System diagrams for other PB Portfolio projects that have gotten ATOs:
* https://github.com/HHS/TANF-app/blob/main/docs/Security-Compliance/boundary-diagram.md
* https://github.com/HHS/Head-Start-TTADP/blob/main/docs/boundary_diagram.md

**Comment by amymok** [comment]
Potential diagram tools:

- TANF: [Draw.io](https://app.diagrams.net/)
  - Pros: feature-rich diagram tool; can use different icons (i.e. AWS icons) to create easy-to-read diagram; it can 
  - Cons: It is not diagram-as-code; exporting to XML does not show the structure of the diagram
- HeadStart TTADP: [C4 variant of PlantUML](https://github.com/RicardoNiepel/C4-PlantUML)
  - Pros: Diagram as code, can version control the code
  - Cons: The syntax and style is somewhat limited, and although possible, when altering from the existing syntax and style, it is somewhat hard to do.

**Comment by carjug** [comment]
The completion of this task won't be "Done" until next week when all the engineers can get together and create the diagram collaboratively, but we will get started on initial investigation and leaving thoughts/comments this week.

**Comment by carjug** [comment]
My initial attempts to capture what we currently know about our system's architecture. Let's definitely iterate on this together and do some live pairing! I think that will yield more fruitful results, because I definitely had big questions in my mind about how we should document our database/migration, etc.

![Start of a Diagram](https://user-images.githubusercontent.com/10871517/124330805-65177b80-db4b-11eb-9e27-7be0ccd2cca7.png)

**Comment by ninamak** [comment]
Next steps:

- [ ] Eng co-work to collaborate on this diagram
