### ISSUE TITLE
Get MAPS DB documentation work to a good stopping point

### ISSUE THREAD

**Issue by carjug** [18F/OPRE-Unicorn#42]
- [x] Get the database folder organized
- [x] Make sure all files in the folder is organized
- [x] Create an index on what documentation is available
- [x] Document what else is left to do that can be worked on later

**Comment by amymok** [comment]
Everything is organized in [Database folder](https://drive.google.com/drive/folders/1stDcnEyB9bnYh4V_0CXeS7-P9V5sxfEL).

The index on how to use the folder and other associated working files are documented in [Database Analysis Doc](https://docs.google.com/document/d/1CpGxd4Ptx6m_9Lnm9SmfIFMyaC-9jw8P8um28YC1_s4/edit#)

A todo list is also added in this document when we have time and need to understand the database more in depth.

**Comment by ninamak** [comment]
@amymok Is there anything you're waiting on to be able to mark this as done?

**Comment by amymok** [comment]
Nope! I will move it to done!
