### ISSUE TITLE
Determine if DB testing can be done in TTS sandbox

### ISSUE THREAD

**Issue by ninamak** [18F/OPRE-Unicorn#61]

**Comment by carjug** [comment]
In my initial investigation into this, it appears that our default permissions, as developers in the TTS Sandbox do not allow us to have full autonomy over creating all of the necessary resources associated with a AWS DMS migration. This means that we need to ask for these specific permissions from TTS IT services and then see what they say and go from there. 

<img width="286" alt="Screen Shot 2021-07-08 at 4 20 10 PM" src="https://user-images.githubusercontent.com/10871517/124998412-9db2cb80-e009-11eb-857d-31621cf66bab.png">

<img width="824" alt="Screen Shot 2021-07-08 at 4 18 59 PM" src="https://user-images.githubusercontent.com/10871517/124998432-a4d9d980-e009-11eb-97c9-5d1e7cfba9ed.png">

**Comment by ninamak** [comment]
@carjug Amy and I were writing up tasks for starting the DB testing work (assuming TTS Sandbox can work) and were wondering if you were able to find out if we'd have permission to set up VPC peering in our TTS Sandbox?

**Comment by carjug** [comment]
@ninamak We don't even have permissions to do the most baseline level stuff for an AWS DMS test (create replication instances), let alone VPC peering. The above comment states that we'll need to ask the TTS Tech Portfolio for this if we want them changed.

**Comment by carjug** [comment]
I'll create another card and put it in the backlog for contacting the TTS Tech Portfolio about potentially changing our permissions.

**Comment by carjug** [comment]
Card #72 created.
