### ISSUE TITLE
Set up speed feedback sessions

### ISSUE THREAD

**Issue by ninamak** [18F/OPRE-Unicorn#67]
### Goals
* To establish a forum that allows teammates to give and receive feedback to each other on a regular basis.

### Tasks

- [ ] Determine cadence and format for speed feedback sessions
- [ ] Send calendar invites

### Preferences
| | Nina | Carly | Amy | Alex |
|--|--|--|--|--|
| Format | Agree, Amy's questions look good to me! | Love Amy's Qs | A few questions like these:<ul><li>What do I do well?</li><li>What should I improve on?</li><li>How can I help you?</li></ul>  | Amy's questions look good to me! |
| Frequency | Every cycle | Every cycle  | No preference, something like every 1 to 2 cycles | Every cycle, meaning every 2 weeks |
| Amount of time | 15 mins |  15 mins | 15 mins | 15 mins |
| Any notes on preferences, i.e. time of day, specific day in the week | I'd actually prefer NOT to use our co-work block for this.  It's helpful to have those times available for meeting or scheduling project-related meetings or getting head's down work done.  Maybe 15 min after our Thurs co-work (after a break)? | I agree to not take up co-work time for this, but no preference otherwise! | No preference | How about we hold the end of our Thursday coworking block for speed feedback every other week?

**Comment by amymok** [comment]
I started a table here, we can put in our preference on how we vision this.

**Comment by alexsoble** [comment]
@amymok Great, added my two cents!

**Comment by amymok** [comment]
@ninamak @carjug Any thoughts on this?

**Comment by ninamak** [comment]
Sorry for the delay!  Added my thoughts to the table.  I'm pretty flexible about it all!

**Comment by carjug** [comment]
Added my thoughts as well!

**Comment by amymok** [comment]
Thanks for all the thoughts here!  I was looking at our calendar to see what would be the best time for this to happen.  If we want to do at a set time together, we will need to block off ~45 mins to give everyone a chance to talk to others.  But it doesn't look like we have an 1-hr open slot until Thursday 8/12 right after our co-work (and same Thursday slot is open biweekly).  This is also the middle of the cycle.  Another 1.5-hr open slot is Wednesday 8/18 right after our co-work (and same Wednesday slot is open biweekly), this will be roughly the end of the cycle, but happens on a Wednesday.

So I would suggest I will at least reserve the time either the Wed or Thursday open slots, and I will have to dig thru calendars, to see if I can match up folks for feedback sessions for this week and the 2 weeks after before we have a more regular cadence.

Any preference on Wednesday end-cycle, or Thursday mid-cycle slot?

**Comment by ninamak** [comment]
I just noticed that this issue is assigned to me, but I have no idea why!  If there's something you need me to do with this, please let me know, cuz I have no clue :)

**Comment by amymok** [comment]
I was able to reserve a 30-min slot (using the template Nina suggested above) to do speed feedback during end of cycle on Thursday after our co-work.  I started it on Aug 5th by realize there's couple conflicts there, so for the 1st one, I moved it to the 12th.  But leaving the other ones in place.  Understand that there may be time that we are out of office or have conflicts, we can decide as pairs if we want to move it to another time or skip.

Will see how that works out!

**Comment by ninamak** [comment]
Thank you!!

**Comment by amymok** [comment]
@ninamak @alexsoble @carjug Anything else we want to address before I close this?  We can start another issue later if things are not working out well.  But we do have a schedule right now.

**Comment by carjug** [comment]
Nope! Having things on the calendar seems like a good place to stop for me.

**Comment by ninamak** [comment]
LGTM!  I added it to the ["Meetings" section of our Project ReadMe](https://docs.google.com/document/d/1UQGQBCoiUzHSdpvyLQrS5GtTtQXjNrKHYy3y_SXED1k/edit#heading=h.n3gtfyokdfav)

**Comment by alexsoble** [comment]
👍 👍 👍

**Comment by alexsoble** [comment]
I think this is "Done" now huh?!?
