### ISSUE TITLE
Decide on tool for document storage and create ADR for it

### ISSUE THREAD

**Issue by carjug** [18F/OPRE-Unicorn#68]

**Comment by amymok** [comment]
Is there any other options other than S3 we would like to consider?

**Comment by carjug** [comment]
Personally, I don't think so, given that any other options would like require a procurement and exist outside the AWS/cloud.gov pattern.

**Comment by alexsoble** [comment]
Agreed, I wouldn't consider options besides S3 given the reasons @carjug mentioned above.

**Comment by amymok** [comment]
Thanks for the information.  I can start the ADR later today!

**Comment by carjug** [comment]
Moving to "Done"!
