### ISSUE TITLE
Epic: Define vision and roadmap

### ISSUE THREAD

**Issue by ninamak** [18F/OPRE-Unicorn#9]
### Goals
- Have a vision for what problems a rebuilt MAPS is expected to address and the impact it would have.
- Have a roadmap that breaks down how we will rebuild MAPS, with higher fidelity for the work we'll take on now and lower fidelity for the work that will come later.

### Approach
- Determine whether the scope of MAPS could/should be expanded to meet other unmet needs of the Office of the Director
- Identify existing functionality that will need to be supported by the new system
- Identify new/improved functionality that is desired in the new system
- Prioritize
- Identify risks
- Work with tech lead to map out milestones that take into consideration user/org priorities and technical considerations
  - Consider "module" or "encapsulation" approach vs "walking skeleton" approach

**Comment by alexsoble** [comment]
@ninamak presented an initial draft Product Vision to executive stakeholders in our check-in meeting today.

**Comment by alexsoble** [comment]
Should we pull this Epic into Milestone 0?

**Comment by ninamak** [comment]
@alexsoble Now that I've had a chance to review this Epic, I think it's largely still applicable.  We've done pieces of it but not all, and it would be helpful to track the stories that are part of this work.  With the limitations of GH Projects, I think we may need to use the Milestones feature, as opposed to using labels to jury-rig Epics.

**Proposal**
* Use Milestones when there's a collection of stories needed to achieve a goal.  The Milestones features lets us prioritize/sequence stories and track progress (whereas Labels do not provide this functionality).
* Use one Project Board per Cycle to keep track of the specific work we're focused on.  This work can come from one or more Milestones, but a good practice would be to limit to no more than 2-3 Milestones at a time so that our attention isn't too divided.
* Use a Backlog column on the Project Board to collect possible stories we'd consider pulling into the sprint and prioritize against each other (because there's no other good way to see stories across Milestones)

Thoughts @alexsoble @carjug @amymok ?

**Comment by carjug** [comment]
That makes sense to me. So just so I'm understanding correctly "Milestones" in the GH world would be our epics?

**Comment by ninamak** [comment]
<<Shruggie>>  What's the difference between a Milestone and an Epic?  (I've seen them defined differently and interchangeably, so I'd be curious what connotations those words have for the rest of you all.)

**Comment by carjug** [comment]
Oh I'm just used to using the word Epic, I've not really used the word Milestone before. I was just double checking to see if the two mean the same thing?

**Comment by ninamak** [comment]
Converted to [Milestone 0.5](https://github.com/18F/OPRE-Unicorn/milestone/4)
